# Commented university codes do not appear in lærested_for_studenter.csv

valid_uni_codes = {
        "NHH": "Norges Handelshøyskole",
        "HVL": "Høgskulen på Vestlandet",
        # "FIH": "",
        "UIB": "Universitetet i Bergen",
        # "AHS": "",
        "HIØ": "Høgskolen i Østfold",
        "NTNU": "Norges teknisk-naturvitenskapelige universitet",
        "SA/SH": "Sámi allaskuvla - Samisk høgskole",
        "DMMH": "Dronning Mauds Minne Høgskole for barnehagelærerutdanning",
        "MF": "MF vitenskapelig høyskole for teologi, religion og samfunn",
        "NIH": "Norges idrettshøgskole",
        # "UIT": "",
        "HVO": "Høgskulen i Volda",
        "HINN": "Høgskolen i Innlandet",
        "UIS": "Universitetet i Stavanger",
        "PHS": "Politihøgskolen",
        "USN": "Universitetet i Sørøst-Norge",
        "NMBU": "Norges miljø- og biovitenskapelige universitet",
        # "LDH": "",
        "AHO": "Arkitektur- og designhøgskolen i Oslo",
        "OSLOMET": "OsloMet - storbyuniversitetet",
        "NORD": "Nord universitet",
        # "HIM": "",
        "VID": "VID vitenskapelige høgskole",
        "UIA": "Universitetet i Agder",
        "NLA": "NLA Høgskolen",
        "UIO": "Universitetet i Oslo"
    }

uni_codes = {
        "NHH": "Norges Handelshøyskole",
        "HVL": "Høgskulen på Vestlandet",
        "FIH": "Fjellhaug Internasjonale Høgskole",
        "UIB": "Universitetet i Bergen",
        "AHS": "Ansgar høyskole",
        "HIØ": "Høgskolen i Østfold",
        "NTNU": "Norges teknisk-naturvitenskapelige universitet",
        "SA/SH": "Sámi allaskuvla - Samisk høgskole",
        "DMMH": "Dronning Mauds Minne Høgskole for barnehagelærerutdanning",
        "MF": "MF vitenskapelig høyskole for teologi, religion og samfunn",
        "NIH": "Norges idrettshøgskole",
        "UIT": "UiT Norges arktiske universitet",
        "HVO": "Høgskulen i Volda",
        "HINN": "Høgskolen i Innlandet",
        "UIS": "Universitetet i Stavanger",
        "PHS": "Politihøgskolen",
        "USN": "Universitetet i Sørøst-Norge",
        "NMBU": "Norges miljø- og biovitenskapelige universitet",
        "LDH": "Lovisenberg diakonale høgskole",
        "AHO": "Arkitektur- og designhøgskolen i Oslo",
        "OSLOMET": "OsloMet - storbyuniversitetet",
        "NORD": "Nord universitet",
        "HIM": "Høgskolen i Molde",
        "VID": "VID vitenskapelige høgskole",
        "UIA": "Universitetet i Agder",
        "NLA": "NLA Høgskolen",
        "UIO": "Universitetet i Oslo"
    }